### ISSUE TITLE
Move filters to the left of search

### ISSUE THREAD

**Issue by rfairooz** [acm-ucr/gamespawn-website#140]
move filters, make the spacing like the Figma, do not worry about UI for checkboxes or the text

<img width="799" alt="Screenshot 2024-05-20 at 6 17 18 PM" src="https://github.com/acm-ucr/gamespawn-website/assets/91511317/6147ff2d-9b69-4d88-a22e-852abca329bd">

**Comment by atharvanev** [comment]
I think its already on the left
