### ISSUE TITLE
Home - Project Display Component

### ISSUE THREAD

**Issue by rfairooz** [acm-ucr/gamespawn-website#32]
The initial projects that are displayed in this section, we will create a component called ProjDisplay for it.
File to code in: src/components/home/ProjDisplay.js
Props: image, title
<img width="1421" alt="Screenshot 2024-04-03 at 5 49 28 PM" src="https://github.com/acm-ucr/gamespawn-website/assets/91511317/0cc80811-9edc-4d03-b49e-3ffb21c66507">

**Comment by Maduz0097** [comment]
Can you assign this issue to me?
