### ISSUE TITLE
Ongoing Project Card

### ISSUE THREAD

**Issue by rfairooz** [acm-ucr/gamespawn-website#34]
Create the component for this card. File to code in: src/components/projects/ongoing/ProjCard.js
Props: title, image, summary.

<img width="756" alt="Screenshot 2024-04-03 at 5 59 59 PM" src="https://github.com/acm-ucr/gamespawn-website/assets/91511317/aa7cb6e7-2d95-49e1-8726-caaf2ec3feca">

**Comment by jyo142** [comment]
hello @rfairooz is this still an issue? If so would love to give it a try
